### ISSUE TITLE
Controller has removed CNAME record from Route53

### ISSUE THREAD

**Issue by tereschenkov** [coreos/alb-ingress-controller#104]
Controller successfuly created an ALB, but at the same time it removed one of a records:

```
I0518 11:31:14.796347       1 elbv2.go:43] Request: elasticloadbalancing/&{CreateLoadBalancer POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  Name: "test-flq-123",
  Scheme: "internal",
  SecurityGroups: ["sg-123"],
  Subnets: ["subnet-123","subnet-234","subnet-345"],
  Tags: [{
      Key: "Namespace",
      Value: "echoserver"
    },{
      Key: "IngressName",
      Value: "echoserver"
    },{
      Key: "Hostname",
      Value: "echo1.k8s.example.com"
    }]
}
I0518 11:31:15.259183       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Completed ELBV2 (ALB) creation. Name: test-flq-b1db346956a391a | ARN: arn:aws:elasticloadbalancing:eu-west-1:123123:loadbalancer/app/test-flq-123/123
I0518 11:31:15.259201       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start Route53 resource record set creation.
I0518 11:31:15.259409       1 route53.go:50] Request: route53/&{ListResourceRecordSets GET /2013-04-01/hostedzone/{Id}/rrset %!s(*request.Paginator=&{[StartRecordName StartRecordType StartRecordIdentifier] [NextRecordName NextRecordType NextRecordIdentifier] MaxItems IsTruncated}) %!s(func(*request.Request) error=<nil>)}, Payload: {
  HostedZoneId: "/hostedzone/ZN123123",
  MaxItems: "100",
  StartRecordName: "echo1.k8s.example.com",
  StartRecordType: "A"
}
I0518 11:31:15.358396       1 route53.go:50] Request: route53/&{ChangeResourceRecordSets POST /2013-04-01/hostedzone/{Id}/rrset/ %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  ChangeBatch: {
    Changes: [{
        Action: "DELETE",
        ResourceRecordSet: {
          Name: "mailer.example.com.",
          ResourceRecords: [{
              Value: "123.234.sendgrid.net"
            }],
          TTL: 300,
          Type: "CNAME"
        }
      }]
  },
  HostedZoneId: "/hostedzone/ZN123123"
}
E0518 11:31:15.514260       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/usr/lib/go/src/runtime/asm_amd64.s:479
/usr/lib/go/src/runtime/panic.go:458
/usr/lib/go/src/runtime/panic.go:62
/usr/lib/go/src/runtime/sigpanic_unix.go:24
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:127
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:86
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:63
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:24
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2086
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x84c429]
goroutine 82 [running]:
panic(0x16d4600, 0xc420014030)
        /usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x16d4600, 0xc420014030)
        /usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).delete(0xc42031aea0, 0xc4206c32c0, 0xc42061d940, 0x444424)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:127 +0x3b9
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).create(0xc42031aea0, 0xc4206c32c0, 0x48, 0x18c739d)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:86 +0x9e
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).SyncState(0xc42031aea0, 0xc4206c32c0, 0x0)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:63 +0x4d7
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.SyncState(0xc420120a98, 0x1, 0x1, 0x2408700, 0xc4202deee0, 0x2408700)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:24 +0xa0
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).SyncState(0xc420539270)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344 +0x81
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420283950, 0xc420347518, 0x0, 0x8, 0xc4201d9a60, 0x2, 0x2, 0x2477f88, 0x0, 0x0)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).sync(0xc4204e70e0, 0x15f3960, 0xc4206283b0, 0xc4206283b0, 0xc420628300)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 +0x68f
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.sync)-fm(0x15f3960, 0xc4206283b0, 0xa, 0xc4201b7dc0)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4201f4a80)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 +0x101
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc42061df58)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42061df58, 0x12a05f200, 0x0, 0x1, 0xc420418000)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc42061df58, 0x12a05f200, 0xc420418000)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4201f4a80, 0x12a05f200, 0xc420418000)
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x55
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
        /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1081 +0x1f1
```

**Comment by joshrosso** [comment]
@tereschenkov, this does sound like an older issue. Can you verify you're using a newer version of the controller (versions: https://quay.io/repository/coreos/alb-ingress-controller?tag=latest&tab=tags).

We're going to refine our versioning scheme soon, but for now it's just based on git hashes.

Let me know, thanks!

**Comment by tereschenkov** [comment]
@joshrosso I've used kube config from examples folder. Just saw it uses  quay.io/coreos/alb-ingress-controller:0.8, will try latest image today

**Comment by tereschenkov** [comment]
The last version works fine. No error
