### ISSUE TITLE
ALB Controller Not Picking Up On Resource Changes

### ISSUE THREAD

**Issue by transient1** [coreos/alb-ingress-controller#124]
I hope this is the right place to put this. I successfully deployed an alb ingress with two backends defined in the resource manifest. 

```apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "alb-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/subnets: subnet-3319b90f,subnet-8cbb33a1,subnet-dc582395,subnet-fdef62a6
    alb.ingress.kubernetes.io/security-groups: sg-c5c419b4
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:xxxxxxxxx
    kubernetes.io/ingress.class: "alb"
  labels:
    app: alb-in
spec:
  rules:
  - host: apps.stage.internal.engineering
    http:
      paths:
      - path: /eightyeighty
        backend:
          serviceName: "backend-svc-1"
          servicePort: 80
      - path: /web
        backend:
          serviceName: "web"
          servicePort: 80```

However, when I changed the /web path to something else and updated with `kubectl update -f alb-ingress-resource.yaml` , the controller seemed to get stuck and started responding with backend-svc-1 for all requests, no matter what uri I used. I tried changing the paths, and even removed the /eightyeighty path, but the controller still forwarded requests to that backend. The only thing I saw logged in the controller was 

```I0622 19:47:12.693024       1 log.go:48] [ALB-INGRESS] [default-alb-ingress] [INFO]: Start TargetGroup deletion.
I0622 19:47:12.693848       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"alb-ingress", UID:"a83eb999-577b-11e7-918a-12b67614d9ae", APIVersion:"extensions", ResourceVersion:"48488392", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/alb-ingress
I0622 19:48:53.863977       1 log.go:48] [ALB-INGRESS] [default-alb-ingress] [INFO]: Completed TargetGroup deletion.
I0622 19:48:53.864041       1 log.go:48] [ALB-INGRESS] [default-alb-ingress] [INFO]: Start Rule deletion.
I0622 19:48:54.007234       1 log.go:48] [ALB-INGRESS] [default-alb-ingress] [INFO]: Completed Rule deletion. Rule: [{    Field: "path-pattern",    Values: ["/eightyeighty"]  }] | Condition: %!s(MISSING)
I0622 19:48:54.007711       1 controller.go:420] ingress backend successfully reloaded...
I0622 19:48:54.008418       1 controller.go:420] ingress backend successfully reloaded...
I0622 19:48:56.339585       1 controller.go:420] ingress backend successfully reloaded...
I0622 19:49:00.568512       1 controller.go:420] ingress backend successfully reloaded...
I0622 19:49:03.898233       1 controller.go:420] ingress backend successfully reloaded...
I0622 19:49:06.352127       1 controller.go:420] ingress backend successfully reloaded...```

I then decided to try and delete the resource all together and recreate it. I was tailing the controller pod logs at the same time. This happened when I ran the create statement:

```I0622 20:05:29.375168       1 log.go:48] [ALB-INGRESS] [default-alb-ingress] [INFO]: Start ELBV2 (ALB) creation.
I0622 20:05:29.850662       1 log.go:48] [ALB-INGRESS] [default-alb-ingress] [INFO]: Completed ELBV2 (ALB) creation. Name: stg-k8s-0a902518bd4652c | ARN: arn:aws:elasticloadbalancing:us-east-1:267230788984:loadbalancer/app/stg-k8s-0a902518bd4652c/e7e498f07b10fefa
E0622 20:05:29.851000       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:350
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1490a57]

goroutine 77 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
..........```

I deleted the controller and the ingress, and recreated them both and it's working again.

**Comment by bigkraig** [comment]
All of the rule and listener code has been reworked over the last couple of weeks. Can you verify that this is still a problem with the current master?

**Comment by joshrosso** [comment]
Added comments to https://github.com/coreos/alb-ingress-controller/issues/124

I believe this is fixed in the newest version as mentioned by @bigkraig. Please feel free to reopen if not.
