### ISSUE TITLE
Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by lypht** [coreos/alb-ingress-controller#125]
Hello!

I've successfully created the alb-ingress-controller using helm and have made it past issues with roles and ARN policies.  I am running into the following:

```
E0622 20:36:11.982314       1 route53.go:143] Failed to lookup resource record set REDACTED, with request {
  HostedZoneId: "/hostedzone/REDACTED",
  MaxItems: "1",
  StartRecordName: "REDACTED",
  StartRecordType: "A"
}
E0622 20:36:22.097127       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
```

As luck would have it, my name is Josh as well, which sent me down an unhappy path the details of which I'll spare.  Has anyone else encountered this?  I'm happy to provide any additional non-confidential information.  Thanks in advance.

**Comment by lypht** [comment]
In looking at that go util, I realized it's just the panic function, which isn't too helpful.  Here's the remainder of the log until the pod crashes:
```
I0622 20:48:19.615616       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0622 20:48:19.615883       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0622 20:48:19.880392       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Fetching resource recordset for telemundo/tmund-nginx telemundo.ots-sandbox.containers.nbcuext.com
E0622 20:48:19.900619       1 route53.go:143] Failed to lookup resource record set telemundo.ots-sandbox.containers.nbcuext.com, with request {
  HostedZoneId: "/hostedzone/ZOQCDGO8MN2PZ",
  MaxItems: "1",
  StartRecordName: "telemundo.ots-sandbox.containers.nbcuext.com",
  StartRecordType: "A"
}
I0622 20:48:19.900657       1 log.go:62] [ALB-INGRESS] [controller] [ERROR]: Failed to find telemundo.ots-sandbox.containers.nbcuext.com in AWS Route53
I0622 20:48:19.940037       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 1 ingresses from existing AWS resources
I0622 20:48:19.940116       1 launch.go:101] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0622 20:48:19.940137       1 launch.go:104] Watching for ingress class: alb
I0622 20:48:19.940341       1 launch.go:257] Creating API server client for https://10.35.0.1:443
I0622 20:48:19.952857       1 launch.go:120] validated kube-system/alb-alb-ingress-controller-helm-default-backend as the default backend
I0622 20:48:19.971702       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Ingress class set to alb
I0622 20:48:19.971724       1 controller.go:1183] starting Ingress controller
I0622 20:48:19.972327       1 leaderelection.go:203] attempting to acquire leader lease...
I0622 20:48:19.976849       1 controller.go:174] ignoring add for ingress tectonic-ingress based on annotation kubernetes.io/ingress.class with value tectonic
I0622 20:48:19.977210       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"telemundo", Name:"tmund-nginx", UID:"a607178e-5788-11e7-ae43-027fae2df16a", APIVersion:"extensions", ResourceVersion:"41197916", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress telemundo/tmund-nginx
W0622 20:48:20.972610       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0622 20:48:20.977118       1 queue.go:88] requeuing telemundo/tmund-nginx, err deferring sync till endpoints controller has synced
I0622 20:48:22.701064       1 log.go:48] [ALB-INGRESS] [telemundo-tmund-nginx] [INFO]: Start Route53 resource record set creation.
E0622 20:48:22.717144       1 route53.go:143] Failed to lookup resource record set telemundo.ots-sandbox.containers.nbcuext.com, with request {
  HostedZoneId: "/hostedzone/ZOQCDGO8MN2PZ",
  MaxItems: "1",
  StartRecordName: "telemundo.ots-sandbox.containers.nbcuext.com",
  StartRecordType: "A"
}
E0622 20:48:32.811612       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:194
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:105
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:165
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:77
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:350
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa5dbad]
goroutine 100 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1719ca0, 0x2571af0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/awsutil.(*Route53).verifyRecordCreated(0xc42030e660, 0xc4205290a0, 0x16, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:194 +0xdd
github.com/coreos/alb-ingress-controller/awsutil.(*Route53).Modify(0xc42030e660, 0xc42052e340, 0xc420399348, 0xc420012820, 0x444bb5)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:105 +0x20f
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).modify(0xc420806660, 0xc420090960, 0x3a, 0x1)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:165 +0x256
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).create(0xc420806660, 0xc420090960, 0x39, 0x1940b4d)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:112 +0xb7
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0xc420806660, 0xc420090960, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:77 +0x6fb
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42000c100, 0x1, 0x1, 0xc42000cd20, 0xc42048a730, 0xc42000cd20, 0xc42013e340, 0x3ff0000000000000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26 +0xb7
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc42048a730)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:350 +0x9a
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420305560, 0x25a6008, 0x0, 0x0, 0xc420143e30, 0x2, 0x2, 0x25a6008, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc4206cfcc0, 0x16159a0, 0xc42033f3d0, 0xc42033f3d0, 0xc4202d0300)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413 +0x805
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.syncIngress)-fm(0x16159a0, 0xc42033f3d0, 0xa, 0xc42073cdf8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4202b0360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207c2fa8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420af5fa8, 0x2540be400, 0x0, 0x1, 0xc420352360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207c2fa8, 0x2540be400, 0xc420352360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4202b0360, 0x2540be400, 0xc420352360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1192 +0x223
```

**Comment by lypht** [comment]
In looking at that go utility, I realized what I've shared above is just the function to handle a panic.  Here's the remainder of the log until the pod crashes:
```
I0622 20:48:19.615616       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0622 20:48:19.615883       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0622 20:48:19.880392       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Fetching resource recordset for NAMESPACE/REDACTED_URL
E0622 20:48:19.900619       1 route53.go:143] Failed to lookup resource record set REDACTED_URL, with request {
  HostedZoneId: "/hostedzone/REDACTED_HOSTEDZONE",
  MaxItems: "1",
  StartRecordName: "REDACTED_URL",
  StartRecordType: "A"
}
I0622 20:48:19.900657       1 log.go:62] [ALB-INGRESS] [controller] [ERROR]: Failed to find REDACTEDURL in AWS Route53
I0622 20:48:19.940037       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 1 ingresses from existing AWS resources
I0622 20:48:19.940116       1 launch.go:101] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0622 20:48:19.940137       1 launch.go:104] Watching for ingress class: alb
I0622 20:48:19.940341       1 launch.go:257] Creating API server client for https://10.35.0.1:443
I0622 20:48:19.952857       1 launch.go:120] validated kube-system/alb-alb-ingress-controller-helm-default-backend as the default backend
I0622 20:48:19.971702       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Ingress class set to alb
I0622 20:48:19.971724       1 controller.go:1183] starting Ingress controller
I0622 20:48:19.972327       1 leaderelection.go:203] attempting to acquire leader lease...
I0622 20:48:19.976849       1 controller.go:174] ignoring add for ingress tectonic-ingress based on annotation kubernetes.io/ingress.class with value tectonic
I0622 20:48:19.977210       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"REDACTED", Name:"REDACTED", UID:"REDACTED", APIVersion:"extensions", ResourceVersion:"41197916", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress NAMESPACE/REDACTED_INGRESS_NAME
W0622 20:48:20.972610       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0622 20:48:20.977118       1 queue.go:88] requeuing NAMESPACE/REDACTED_INGRESS_NAME, err deferring sync till endpoints controller has synced
I0622 20:48:22.701064       1 log.go:48] [ALB-INGRESS] [NAMESPACE/REDACTED_INGRESS_NAME] [INFO]: Start Route53 resource record set creation.
E0622 20:48:22.717144       1 route53.go:143] Failed to lookup resource record set REDACTED_URL, with request {
  HostedZoneId: "/hostedzone/REDACTED_HOSTED_ZONE",
  MaxItems: "1",
  StartRecordName: "REDACTED_URL",
  StartRecordType: "A"
}
E0622 20:48:32.811612       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:194
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:105
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:165
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:77
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:350
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa5dbad]
goroutine 100 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1719ca0, 0x2571af0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/awsutil.(*Route53).verifyRecordCreated(0xc42030e660, 0xc4205290a0, 0x16, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:194 +0xdd
github.com/coreos/alb-ingress-controller/awsutil.(*Route53).Modify(0xc42030e660, 0xc42052e340, 0xc420399348, 0xc420012820, 0x444bb5)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/route53.go:105 +0x20f
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).modify(0xc420806660, 0xc420090960, 0x3a, 0x1)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:165 +0x256
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).create(0xc420806660, 0xc420090960, 0x39, 0x1940b4d)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:112 +0xb7
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0xc420806660, 0xc420090960, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:77 +0x6fb
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42000c100, 0x1, 0x1, 0xc42000cd20, 0xc42048a730, 0xc42000cd20, 0xc42013e340, 0x3ff0000000000000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26 +0xb7
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc42048a730)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:350 +0x9a
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420305560, 0x25a6008, 0x0, 0x0, 0xc420143e30, 0x2, 0x2, 0x25a6008, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc4206cfcc0, 0x16159a0, 0xc42033f3d0, 0xc42033f3d0, 0xc4202d0300)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413 +0x805
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.syncIngress)-fm(0x16159a0, 0xc42033f3d0, 0xa, 0xc42073cdf8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4202b0360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207c2fa8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420af5fa8, 0x2540be400, 0x0, 0x1, 0xc420352360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207c2fa8, 0x2540be400, 0xc420352360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4202b0360, 0x2540be400, 0xc420352360)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1192 +0x223
```

**Comment by efim-a-efim** [comment]
Same problem. Just after first ingress appeared :(

**Comment by transient1** [comment]
Same thing here. I reported it a few days ago, but I don't think I got to the heart of the problem as succinctly as this issue.

**Comment by chrismoos** [comment]
This took me a while to figure out but the `host` field must be a domain that can be managed by the ingress controller via Route 53. For example, there must be a Route 53 zone `domain.com` in your AWS account that can be managed by the ingress controller (also ensure proper IAM policy):

```
spec:
  rules:
  - host: service.domain.com
```

If your target domain is externally managed (or otherwise not accessible) you can just update the `host` field to be one that is managed (probably something in your Kubernetes cluster's DNS zone) and then just do a `CNAME` for `service.domain.com` to point to that.

**Comment by bigkraig** [comment]
The latest master branch will update the ingress with the ALB hostname, allowing you to use the external-dns controller to manage DNS outside of the alb-ingress-controller, which is recommended.
