### ISSUE TITLE
Panic on startup

### ISSUE THREAD

**Issue by weaseal** [coreos/alb-ingress-controller#143]
The alb-ingress-controller pod is hitting a panic on startup:

```2017-07-14T17:47:38.912216887Z I0714 17:47:38.912084       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
2017-07-14T17:47:38.914734272Z I0714 17:47:38.914658       1 util.go:98] Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {
2017-07-14T17:47:38.914753288Z   PageSize: 100
2017-07-14T17:47:38.914757789Z }
2017-07-14T17:47:39.011688485Z I0714 17:47:39.011607       1 util.go:98] Request: elasticloadbalancing/&{DescribeTags POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
2017-07-14T17:47:39.011710728Z   ResourceArns: ["arn:aws:elasticloadbalancing:us-west-1:xxxxxxxxxxx:loadbalancer/app/uswest1dev-xxxxxxxxxx/xxxxxxxxxx"]
2017-07-14T17:47:39.011716872Z }
2017-07-14T17:47:39.019571477Z panic: runtime error: index out of range
2017-07-14T17:47:39.019629318Z 
2017-07-14T17:47:39.019636238Z goroutine 1 [running]:
2017-07-14T17:47:39.019640073Z github.com/coreos/alb-ingress-controller/awsutil.(*ELBV2).DescribeTags(0xc42033f790, 0xc4201de268, 0x19491ed, 0xa, 0xc42061db30, 0x1, 0x1)
2017-07-14T17:47:39.019643963Z 	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/awsutil/elbv2.go:293 +0x32e
2017-07-14T17:47:39.019648011Z github.com/coreos/alb-ingress-controller/controller.assembleIngresses(0xc420151b00, 0xc42033f870, 0xc0, 0x190dde0)
2017-07-14T17:47:39.019651406Z 	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:205 +0x256
2017-07-14T17:47:39.019655331Z github.com/coreos/alb-ingress-controller/controller.NewALBController(0xc42013c780, 0xc42032d080, 0x1941f2a)
2017-07-14T17:47:39.019658644Z 	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:41 +0x1a8
2017-07-14T17:47:39.019661726Z main.main()
2017-07-14T17:47:39.019664489Z 	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/main.go:43 +0x24e
```

I have a hunch it's related to IAM permissions as I had been slowly adding them as it hit denials, then after permitting "createloadbalancer", the next startup hit this.

**Comment by weaseal** [comment]
This was related to permissions, once I added the list from this page, the problem went away: https://github.com/coreos/alb-ingress-controller/blob/master/examples/iam-policy.json

**Comment by weaseal** [comment]
I see that this is closed, which is surprising considering that there are unhandled exceptions identified here.  Wouldn't we want to see those cleaned up before closing?  The error message gave 0 helpful output and required scouring the documentation to understand what was wrong.

**Comment by bigkraig** [comment]
A lot of work was done lately to do a better job for catching errors. I've been running the controller with read only permissions and been unable to cause crashes when failing to delete or create resources. thanks for the heads up!
