### ISSUE TITLE
SIGSEGV when host is not provided in ingress

### ISSUE THREAD

**Issue by philloooo** [coreos/alb-ingress-controller#151]
Hi, I am trying the ALB ingress controller for a ingress like this:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: revproxy
  namespace: default
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-9e5aeab2,subnet-fe3f56b6
    alb.ingress.kubernetes.io/security-groups: webservice
    alb.ingress.kubernetes.io/tags: Environment=cdisdev
    alb.ingress.kubernetes.io/certificate-arn: XXX
    alb.ingress.kubernetes.io/backend-protocol: HTTP
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: portal-service
          servicePort: 80
```
After I created the ingress, the controller was able to create the ALB, but it seems to freak out as there is no host so it can't find zoneID?
I saw in https://github.com/coreos/alb-ingress-controller/issues/112 that you plan to support external DNS, that will be great for my use case, do you have a sense when will that happen?

Another thing is that when I delete the ingress, the load balancer is not deleted, is that expected?

Thanks
This is the logs:
```kubectl logs alb-ingress-controller-1659243044-p373f    --namespace kube-system
I0726 17:24:18.922844       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0726 17:24:18.923086       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0726 17:24:19.015007       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Failed to resolve  zoneID. Returned error Unable to find the zone using any subset of hostname: 
I0726 17:24:19.015024       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 0 ingresses from existing AWS resources
I0726 17:24:19.015082       1 launch.go:101] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0726 17:24:19.015731       1 launch.go:257] Creating API server client for https://10.3.0.1:443
I0726 17:24:19.025995       1 launch.go:120] validated kube-system/default-http-backend as the default backend
I0726 17:24:19.036952       1 controller.go:1183] starting Ingress controller
I0726 17:24:19.039496       1 leaderelection.go:203] attempting to acquire leader lease...
I0726 17:24:19.041531       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"revproxy", UID:"058886fa-7227-11e7-a96e-12ee08660b64", APIVersion:"extensions", ResourceVersion:"5096590", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/revproxy
W0726 17:24:20.039903       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0726 17:24:20.041680       1 queue.go:88] requeuing default/revproxy, err deferring sync till endpoints controller has synced
I0726 17:24:21.654374       1 log.go:62] [ALB-INGRESS] [default-revproxy] [ERROR]: Unable to locate ZoneId for .
I0726 17:24:21.654398       1 log.go:48] [ALB-INGRESS] [default-revproxy] [INFO]: Start ELBV2 (ALB) creation.
I0726 17:24:21.950920       1 log.go:48] [ALB-INGRESS] [default-revproxy] [INFO]: Completed ELBV2 (ALB) creation. Name: cdisdev-a21536f9b4d960a | ARN: arn:aws:elasticloadbalancing:us-east-1:562749638216:loadbalancer/app/cdisdev-a21536f9b4d960a/12047b663a60939a
E0726 17:24:21.951041       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1490f97]

goroutine 85 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1719d60, 0x2571af0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0x0, 0xc4209e28f0, 0x0, 0x3)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60 +0x37
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42000c428, 0x1, 0x1, 0x0, 0xc42000c430, 0xc42063d3b0, 0xc42000c430, 0xc420663a60, 0x3ff0000000000000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31 +0x215
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc42063d3b0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356 +0x9d
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc42014d9e0, 0x25a6008, 0x0, 0x0, 0xc42000c030, 0x1, 0x1, 0x25a6008, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc42077c140, 0x1615a00, 0xc42065ab70, 0xc42065ab70, 0xc42065a000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413 +0x805
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.syncIngress)-fm(0x1615a00, 0xc42065ab70, 0xa, 0xc4207fcdf8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc420762f90)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42071efa8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc42075bfa8, 0x2540be400, 0x0, 0x1, 0xc4201a9b60)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42071efa8, 0x2540be400, 0xc4201a9b60)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc420762f90, 0x2540be400, 0xc4201a9b60)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1192 +0x223```

**Comment by max-rocket-internet** [comment]
I have the same issue, I think perhaps the `Unable to locate ZoneId` is not related.

My ingress config:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: maxdev1-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-9999,subnet-99999,subnet-99999
    alb.ingress.kubernetes.io/security-groups: sg-999999db
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  rules:
  - host: maxdev1-ingress.domain.com
    http:
      paths:
      - path: /es
        backend:
          serviceName: maxdev1-es
          servicePort: 9200
      - path: /
        backend:
          serviceName: maxdev1-frontend
          servicePort: 80
```

And pod log:

```
I0821 11:12:32.457889       1 log.go:48] [ALB-INGRESS] [default-maxdev1-ingress] [INFO]: Start ELBV2 (ALB) creation.
I0821 11:12:32.840110       1 log.go:48] [ALB-INGRESS] [default-maxdev1-ingress] [INFO]: Completed ELBV2 (ALB) creation. Name: cluster1-97039aafc064d7f | ARN: arn:aws:elasticloadbalancing:eu-central-1:9999999999:loadbalancer/app/cluster1-97039aafc064d7f/99999999999
E0821 11:12:32.840254       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1490f97]
```

**Comment by bigkraig** [comment]
We've removed Route53 (and all its bugs) from the controller. You can manage DNS with the external-dns controller now.

**Comment by djsd123** [comment]
Thanks @bigkraig. FYI, the docs kind of imply that the records would be handled by the controller. #Documenting-is-hard
