### ISSUE TITLE
Segfault after ALB is created

### ISSUE THREAD

**Issue by gtirloni** [coreos/alb-ingress-controller#190]
Right after the ALB is created, the ALB Ingress Controller dies. 

No listeners are created for that ALB.

**Ingress definition**

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: preferences
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-145542xx,subnet-8fb0e1xx,subnet-9609c2xx
    alb.ingress.kubernetes.io/security-groups: sg-8f1e6fxx
    alb.ingress.kubernetes.io/tags: Environment=dev 
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: preferences
          servicePort: 80
```

**ALB created**:

```
$ aws elbv2 describe-load-balancers --region us-east-1
{
    "LoadBalancers": [
        {
            "LoadBalancerArn": "arn:aws:elasticloadbalancing:us-east-1:4787858067xx:loadbalancer/app/k8s-dev-db340890e3718xx/b04c5b9ba4f849xx",
            "DNSName": "k8s-dev-db340890e371814-12183010xx.us-east-1.elb.amazonaws.com",
            "CanonicalHostedZoneId": "Z35SXDOTRQ7Xxx",
            "CreatedTime": "2017-08-28T13:20:03.360Z",
            "LoadBalancerName": "k8s-dev-db340890e3718xx",
            "Scheme": "internet-facing",
            "VpcId": "vpc-7ba880xx",
            "State": {
                "Code": "active"
            },
            "Type": "application",
            "AvailabilityZones": [
                {
                    "ZoneName": "us-east-1c",
                    "SubnetId": "subnet-145542xx"
                },
                {
                    "ZoneName": "us-east-1b",
                    "SubnetId": "subnet-8fb0e1xx"
                },
                {
                    "ZoneName": "us-east-1a",
                    "SubnetId": "subnet-9609c2xx"
                }
            ],
            "SecurityGroups": [
                "sg-8f1e6fxx"
            ],
            "IpAddressType": "ipv4"
        }
    ]
}
```

```
$ aws elbv2 describe-listeners ...
{
    "Listeners": []
}
```

**Logs**:

```
I0828 13:17:13.742242       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0828 13:17:13.742434       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0828 13:17:13.744941       1 util.go:98] Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {
  PageSize: 100
}
I0828 13:17:13.810916       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 0 ingresses from existing AWS resources
I0828 13:17:13.811013       1 launch.go:101] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0828 13:17:13.811173       1 launch.go:257] Creating API server client for https://100.64.0.1:443
I0828 13:17:13.822135       1 launch.go:120] validated kube-system/default-http-backend as the default backend
I0828 13:17:13.831488       1 controller.go:1183] starting Ingress controller
I0828 13:17:13.831935       1 leaderelection.go:203] attempting to acquire leader lease...
I0828 13:17:13.856372       1 leaderelection.go:213] successfully acquired lease kube-system/ingress-controller-leader-alb
W0828 13:17:14.832509       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0828 13:17:14.837960       1 queue.go:88] requeuing default/couchdb, err deferring sync till endpoints controller has synced
I0828 13:17:16.194668       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:17:17.822539       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:17:19.822555       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:17:21.822564       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:17:23.822573       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:17:25.822593       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:17:27.822537       1 controller.go:420] ingress backend successfully reloaded...
I0828 13:20:02.726193       1 util.go:98] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  SubnetIds: ["subnet-145542xx","subnet-8fb0e1xx","subnet-9609c2xx"]
}
I0828 13:20:02.727000       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"preferences", UID:"99868e32-8bf3-11e7-86b4-021e8e1f6170", APIVersion:"extensions", ResourceVersion:"4898", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress default/preferences
I0828 13:20:02.833184       1 util.go:98] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  SubnetIds: ["subnet-145542xx","subnet-8fb0e1xx","subnet-9609c2xx"]
}
I0828 13:20:02.850797       1 util.go:98] Request: ec2/&{DescribeSecurityGroups POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  GroupIds: ["sg-8f1e6fxx"]
}
I0828 13:20:02.900865       1 ingress.go:113] default-preferences: default/preferences service is not of type NodePort
I0828 13:20:02.900884       1 log.go:48] [ALB-INGRESS] [default-preferences] [INFO]: Start ELBV2 (ALB) creation.
I0828 13:20:02.901067       1 util.go:98] Request: elasticloadbalancing/&{CreateLoadBalancer POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  Name: "k8s-dev-db340890e371814",
  Scheme: "internet-facing",
  SecurityGroups: ["sg-8f1e6fxx"],
  Subnets: ["subnet-145542xx","subnet-8fb0e1xx","subnet-9609c2xx"],
  Tags: [
    {
      Key: "Environment",
      Value: "dev"
    },
    {
      Key: "Namespace",
      Value: "default"
    },
    {
      Key: "IngressName",
      Value: "preferences"
    },
    {
      Key: "Hostname",
      Value: ""
    }
  ]
}
I0828 13:20:03.725982       1 log.go:48] [ALB-INGRESS] [default-preferences] [INFO]: Completed ELBV2 (ALB) creation. Name: k8s-dev-db340890e371814 | ARN: arn:aws:elasticloadbalancing:us-east-1:478785806711:loadbalancer/app/k8s-dev-db340890e371814/b04c5b9ba4f84915
E0828 13:20:03.726095       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1490f97]

goroutine 90 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1719d60, 0x2571af0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0x0, 0xc42066e840, 0x0, 0x3)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60 +0x37
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42000c698, 0x1, 0x1, 0x0, 0xc42000c6a0, 0xc42062ed70, 0xc42000c6a0, 0xc4201c1f70, 0x4020000000000000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31 +0x215
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc42062ed70)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356 +0x9d
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc4201839e0, 0x25a6008, 0x0, 0x0, 0xc42012c230, 0x1, 0x1, 0x25a6008, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc420770dc0, 0x1615a00, 0xc4201c14b0, 0xc4201c14b0, 0xc42034b300)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413 +0x805
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.syncIngress)-fm(0x1615a00, 0xc4201c14b0, 0xa, 0xc420a1bdf8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4207aacc0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4207ae7a8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420a1bfa8, 0x2540be400, 0x0, 0x1, 0xc4202978c0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4207ae7a8, 0x2540be400, 0xc4202978c0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4207aacc0, 0x2540be400, 0xc4202978c0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1192 +0x223
```

**Comment by cyberious** [comment]
I am seeing this as a repeated pattern.

**Comment by olitheolix** [comment]
I had the exact same symptom, but mine was preceded by a Route53 error when
creating the DNS entry. That error, it turned out, was due to missing IAM policies
in my Worker role (got the idea from #61).

The fix, for me at least, was to add the IAM policies to my Worker role.

**Comment by alexmbird** [comment]
I'm having the exact same problem.  

I have kube2iam supplying an IAM role containing the [example policy](https://raw.githubusercontent.com/coreos/alb-ingress-controller/master/examples/iam-policy.json) to my `alb-ingress-controller` pod, but still it crashes with `runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)` immediately after creating the first ALB.

**Comment by joshrosso** [comment]
Hey all, what version of the controller is this observed in? `0.8`?

**Comment by olitheolix** [comment]
@joshrosso Yes, I use 0.8.

@alexmbird Have you set AWS_DEBUG to 'true' (in alb_ingress_controller.yaml)? This will add detailed
info about every call to the AWS API, including the return/error code. It helped my identify my problem.

**Comment by alexmbird** [comment]
@joshrosso `0.8` here as well.

@olitheolix yes, I'm running with `AWS_DEBUG=true`.  The call to create the ALB succeeds, but immediately after that the ingress controller blows up with a segfault.  The output is:

```
I0908 08:25:13.611434       1 log.go:48] [ALB-INGRESS] [default-my-web-app] [INFO]: Start ELBV2 (ALB) creation.
I0908 08:25:13.611599       1 util.go:98] Request: elasticloadbalancing/&{CreateLoadBalancer POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  Name: "kcl-sand-a-151a69ec2f6619a",
  Scheme: "internet-facing",
  SecurityGroups: ["sg-5136ed39"],
  Subnets: ["subnet-5b224620","subnet-9ce04fd1","subnet-c486ddad"],
  Tags: [
    {
      Key: "Environment",
      Value: "intg01"
    },
    {
      Key: "Team",
      Value: "test"
    },
    {
      Key: "Namespace",
      Value: "default"
    },
    {
      Key: "IngressName",
      Value: "my-web-app"
    },
    {
      Key: "Hostname",
      Value: "myapp.inst-1.sandbox-1.mydomain.com"
    }
  ]
}
I0908 08:25:13.864262       1 log.go:48] [ALB-INGRESS] [default-my-web-app] [INFO]: Completed ELBV2 (ALB) creation. Name: kcl-sand-a-151a69ec2f6619a | ARN: arn:aws:elasticloadbalancing:us-east-2:818717841049:loadbalancer/app/kcl-sand-a-151a69ec2f6619a/512654f5dbcbeb50
E0908 08:25:13.864403       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1490f97]

goroutine 81 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1719d60, 0x2571af0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0x0, 0xc42091a000, 0x0, 0x3)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60 +0x37
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42011c560, 0x1, 0x1, 0x0, 0xc42011c568, 0xc420665f40, 0xc42011c568, 0xc42066e910, 0x3ff0000000000000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31 +0x215
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc420665f40)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356 +0x9d
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc42017b8c0, 0x25a6008, 0x0, 0x0, 0xc42066e8a0, 0x2, 0x2, 0x25a6008, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc420776c80, 0x1615a00, 0xc4206b9c20, 0xc4206b9c20, 0xc4206b9c00)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413 +0x805
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.syncIngress)-fm(0x1615a00, 0xc4206b9c20, 0xa, 0xc42003edf8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4207ab5f0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420759fa8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420723fa8, 0x2540be400, 0x0, 0x1, 0xc420115e60)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420759fa8, 0x2540be400, 0xc420115e60)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4207ab5f0, 0x2540be400, 0xc420115e60)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1192 +0x223
```

**Comment by olitheolix** [comment]
@alexmbird: The AWS error I mentioned happens *before* the ELB is created (due to missing
Route53 privileges), even though the segfault happens *after* the ELB was created. Here is how my problem manifests itself in the logs:

> I0910 22:13:47.924884       1 log.go:62] [ALB-INGRESS] [foobar-foobar-ingress] [ERROR]: Unable to locate ZoneId for foobar.net.
> I0910 22:13:47.924911       1 log.go:48] [ALB-INGRESS] [foobar-foobar-ingress] [INFO]: Start ELBV2 (ALB) creation.
> 
I did not include the segfault that happens shortly after. The problem disappears as soon as I provide the correct Route53 permissions (see [here](https://github.com/coreos/alb-ingress-controller/blob/master/examples/iam-policy.json)).

@joshrosso Is there any chance the controller could sanely abort when the AWS API returns an error?

**Comment by alexmbird** [comment]
@olitheolix I suspect I'm seeing a related-but-different problem.  I use `kube2iam` (known to be working for other pods) to give the ingress controller the privs described in the [example](https://github.com/coreos/alb-ingress-controller/blob/master/examples/iam-policy.json) and there are no errors in the output along the lines of `Unable to locate ZoneId`.  

The logs from my `kube2iam` pods contain many lines like:

```time="2017-09-11T09:01:31Z" level=info msg="GET /latest/meta-data/iam/security-credentials/k8s-ingresscontroller-alb-role (200) took 29465 ns" req.method=GET req.path=/latest/meta-data/iam/security-credentials/k8s-ingresscontroller-alb-role req.remote=<ip> res.duration=29465 res.status=200```

...so I'm pretty confident the controller is getting its IAM role.

**Comment by joshrosso** [comment]
We're working towards stabilizing the controller and a lot has changed since 1.0.

Would anyone be willing to try `b30d8d28` and let me know if the permission-based segfault continues? If so, we'll tackle it as part of the `1.0` milestone.

Please include details if it does.

**Comment by alexmbird** [comment]
Awesome, I'm trying it now: an ALB is created and configured and nothing crashes.  It's getting late so I'll check out the resulting setup in the morning.  Thanks for your help!

**Comment by joshrosso** [comment]
Awesome thanks Alex.

**Comment by joshrosso** [comment]
So far in my testing I haven't been able to reproduce this. Feel free to re-open if you can in this newest version.
