### ISSUE TITLE
runtime error possibly caused by 'Unable to find a port defined in the service'

### ISSUE THREAD

**Issue by irishandyb** [coreos/alb-ingress-controller#227]
I have deployed a cluster to AWS via kops.
Once the cluster is deployed, I follow the [AWS guide for prometheus-operator](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/docs/KOPSonAWS.md).

As part of the deployment, a [grafana service](https://github.com/coreos/prometheus-operator/blob/master/contrib/kube-prometheus/manifests/grafana/grafana-service.yaml) is created:

```
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30902
    targetPort: web
  selector:
    app: grafana
```
```
$ kubectl --namespace monitoring describe service grafana
Name:                   grafana
Namespace:              monitoring
Labels:                 app=grafana
Annotations:            ingress.kubernetes.io/named-ports={"web":"3000"}
                        kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"app":"grafana"},"name":"grafana","namespace":"monitoring"},"spec":{"ports":...
Selector:               app=grafana
Type:                   NodePort
IP:                     100.67.218.219
Port:                   <unset> 3000/TCP
NodePort:               <unset> 30902/TCP
Endpoints:              100.96.1.4:3000
Session Affinity:       None
Events:                 <none>```
```
Once the prometheus-operator deployment is up and running, I deploy the [default-backend](https://github.com/coreos/alb-ingress-controller/blob/master/examples/default-backend.yaml) and [alb-ingress-controller](https://github.com/coreos/alb-ingress-controller/blob/master/examples/alb-ingress-controller.yaml).

When the alb-ingress-controller has deployed and is ready, I apply the following ingress controller for the grafana service.

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-1234,subnet-5678
    alb.ingress.kubernetes.io/security-groups: sg-1234,sg-5678
spec:
  rules:
  - host: grafana.cluster.mysite.com
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 30902
```

The expected Route 53 and ALB resources are not deployed to AWS.
I captured the following logs from the alb-ingress-controller deployment:

```
I0928 12:50:35.683494       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0928 12:50:35.683839       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0928 12:50:35.774887       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 0 ingresses from existing AWS resources
I0928 12:50:35.775083       1 launch.go:101] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0928 12:50:35.775372       1 launch.go:257] Creating API server client for https://100.64.0.1:443
I0928 12:50:35.786547       1 launch.go:120] validated kube-system/default-http-backend as the default backend
I0928 12:50:35.795211       1 controller.go:1183] starting Ingress controller
I0928 12:50:35.797196       1 leaderelection.go:203] attempting to acquire leader lease...
I0928 12:50:35.804134       1 event.go:217] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"monitoring", Name:"grafana", UID:"baa85bd3-a44a-11e7-9433-062236b47380", APIVersion:"extensions", ResourceVersion:"5000", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress monitoring/grafana
W0928 12:50:36.797380       1 backend_ssl.go:42] deferring sync till endpoints controller has synced
W0928 12:50:36.803891       1 queue.go:88] requeuing monitoring/grafana, err deferring sync till endpoints controller has synced
I0928 12:50:38.280324       1 ingress.go:113] monitoring-grafana: Unable to find a port defined in the monitoring/grafana service
I0928 12:50:38.280458       1 log.go:48] [ALB-INGRESS] [monitoring-grafana] [INFO]: Start ELBV2 (ALB) creation.
I0928 12:50:38.563791       1 log.go:48] [ALB-INGRESS] [monitoring-grafana] [INFO]: Completed ELBV2 (ALB) creation. Name: k8s-c1-ad8f648cc527258 | ARN: arn:aws:elasticloadbalancing:ap-southeast-1:773503831922:loadbalancer/app/k8s-c1-ad8f648cc527258/d49e1c11be55527b
E0928 12:50:38.564123       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/lib/go/src/runtime/asm_amd64.s:514
/usr/lib/go/src/runtime/panic.go:489
/usr/lib/go/src/runtime/panic.go:63
/usr/lib/go/src/runtime/signal_unix.go:290
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1490f97]

goroutine 62 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1719d60, 0x2571af0)
	/usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0x0, 0xc420af0f20, 0x0, 0x3)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60 +0x37
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42000cbf8, 0x1, 0x1, 0x0, 0xc42000cc00, 0xc4202b9bd0, 0xc42000cc00, 0xc420644c90, 0x3ff0000000000000)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:31 +0x215
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc4202b9bd0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:356 +0x9d
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc42011f170, 0x25a6008, 0x0, 0x0, 0xc420644c30, 0x2, 0x2, 0x25a6008, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:112 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).syncIngress(0xc420350640, 0x1615a00, 0xc420563680, 0xc420563680, 0xc420563600)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:413 +0x805
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.syncIngress)-fm(0x1615a00, 0xc420563680, 0xa, 0xc420637df8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:164 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4204ba420)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:87 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc42060a7a8)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:97 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420711fa8, 0x2540be400, 0x0, 0x5536613348313101, 0xc4201d3ec0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:98 +0xbd
github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc42060a7a8, 0x2540be400, 0xc4201d3ec0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4204ba420, 0x2540be400, 0xc4201d3ec0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1192 +0x223
```

Note that the following line may be of interest as a cause:
`I0928 12:50:38.280324       1 ingress.go:113] monitoring-grafana: Unable to find a port defined in the monitoring/grafana service`

Please advise as to whether this is user error / misconfiguration or an issue with the alb-ingress-controller.

Kind Regards,
Andrew

**Comment by joshrosso** [comment]
Hi @irishandyb

A lot of work is happening with this controller in #197.

Would you be able to try the image version `501862ea` and report back whether these issues persist?

**Comment by joshrosso** [comment]
A cut of `1.0-alpha.3` has been created that includes many stability fixes on panic-related issues. Please re-open this ticket if it persists with the new version.

Thanks for the report!
