### ISSUE TITLE
Panci when reconciling LoadBalancer LIstener

### ISSUE THREAD

**Issue by julianvmodesto** [coreos/alb-ingress-controller#351]
```
alb-ingress-controller-7878c5d9b7-2fgk5 server panic: runtime error: invalid memory address or nil pointer dereference
alb-ingress-controller-7878c5d9b7-2fgk5 server [signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15668be]
alb-ingress-controller-7878c5d9b7-2fgk5 server
alb-ingress-controller-7878c5d9b7-2fgk5 server goroutine 625 [running]:
alb-ingress-controller-7878c5d9b7-2fgk5 server github.com/coreos/alb-ingress-controller/pkg/alb/listeners.Listeners.Reconcile(0xc420293500, 0x4, 0x4, 0xc420915ed8, 0xc42006a150, 0x1, 0x1, 0xc42006a148, 0x1)
alb-ingress-controller-7878c5d9b7-2fgk5 server  /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/alb/listeners/listeners.go:53 +0x1be
alb-ingress-controller-7878c5d9b7-2fgk5 server github.com/coreos/alb-ingress-controller/pkg/alb/loadbalancer.(*LoadBalancer).Reconcile(0xc4201601e0, 0xc420915f58, 0xc4203da8b0, 0x7f9163aa5000, 0x0)
alb-ingress-controller-7878c5d9b7-2fgk5 server  /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/alb/loadbalancer/loadbalancer.go:225 +0x274
alb-ingress-controller-7878c5d9b7-2fgk5 server github.com/coreos/alb-ingress-controller/pkg/albingress.(*ALBIngress).Reconcile(0xc4203ced10, 0xc4201b2fb8)
alb-ingress-controller-7878c5d9b7-2fgk5 server  /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/albingress/albingress.go:321 +0xb4
alb-ingress-controller-7878c5d9b7-2fgk5 server github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).update.func1(0xc4202224e0, 0xc4203ced10)
alb-ingress-controller-7878c5d9b7-2fgk5 server  /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:179 +0xa4
alb-ingress-controller-7878c5d9b7-2fgk5 server created by github.com/coreos/alb-ingress-controller/pkg/controller.(*ALBController).update
alb-ingress-controller-7878c5d9b7-2fgk5 server  /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/pkg/controller/alb-controller.go:177 +0x49e


```

**Comment by bigkraig** [comment]
Should be fixed in #403

**Comment by bigkraig** [comment]
Please test with `1.0-alpha.9` and let me know how it goes
