### ISSUE TITLE
Crash when target group exists

### ISSUE THREAD

**Issue by bigkraig** [coreos/alb-ingress-controller#42]
```
I0412 15:51:12.781889       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Start ELBV2 (ALB) creation.
I0412 15:51:13.340316       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Completed ELBV2 (ALB) creation. Name: dev-cbd8bc1517ff907 | ARN: arn:aws:elasticloadbalancing:us-east-1:343550350117:loadbalancer/app/dev-cbd8bc1517ff907/bedcd33bbcb39731
I0412 15:51:13.340335       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Start Route53 resource record set creation.
I0412 15:51:28.516096       1 status.go:271] updating Ingress tectonic-system/tectonic-ingress status to [{10.188.165.195 }]
I0412 15:51:28.536119       1 event.go:217] Event(api.ObjectReference{Kind:"Ingress", Namespace:"tectonic-system", Name:"tectonic-ingress", UID:"3d031ca5-13e4-11e7-a2da-0e9384040afc", APIVersion:"extensions", ResourceVersion:"4751896", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress tectonic-system/tectonic-ingress
I0412 15:51:28.603953       1 event.go:217] Event(api.ObjectReference{Kind:"Ingress", Namespace:"tectonic-system", Name:"tectonic-ingress", UID:"3d031ca5-13e4-11e7-a2da-0e9384040afc", APIVersion:"extensions", ResourceVersion:"4751898", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress tectonic-system/tectonic-ingress
I0412 15:51:53.951876       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Completed Route 53 resource record set modification. DNS: prometheus.prd123.dev.us-east-1.nonprod-tmaws.io. | Type: A | AliasTarget: {  DNSName: "internal-dev-cbd8bc1517ff907-117324894.us-east-1.elb.amazonaws.com.",  EvaluateTargetHealth: false,  HostedZoneId: "Z35SXDOTRQ7X7K"}
I0412 15:51:53.951924       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Completed Route 53 resource record set creation. DNS: prometheus.prd123.dev.us-east-1.nonprod-tmaws.io | Type: A | Target: {  DNSName: "internal-dev-cbd8bc1517ff907-117324894.us-east-1.elb.amazonaws.com.",  EvaluateTargetHealth: false,  HostedZoneId: "Z35SXDOTRQ7X7K"}.
I0412 15:51:53.951934       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Start TargetGroup creation.
I0412 15:51:54.157843       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Failed TargetGroup creation. Error: DuplicateTargetGroupName: A target group with the same name 'dev-32162-HTTP-df48b9c' exists, but with different settings
	status code: 400, request id: f3466965-1f97-11e7-94ef-557fe64ed15c.
I0412 15:51:54.157871       1 log.go:48] [ALB-INGRESS] [prd123-prom-prometheus] [INFO]: Start Listener creation.
E0412 15:51:54.158045       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/signal_unix.go:290
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:89
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:69
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/listeners.go:30
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x15213d7]
goroutine 120 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x17802c0, 0x254eb40)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*Listener).create(0xc420f1ffc0, 0xc4202f80a0, 0xc420331040, 0x16)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:89 +0x87
github.com/coreos/alb-ingress-controller/controller/alb.(*Listener).SyncState(0xc420f1ffc0, 0xc4202f80a0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:69 +0x17f
github.com/coreos/alb-ingress-controller/controller/alb.Listeners.SyncState(0xc420149630, 0x1, 0x1, 0xc4202f80a0, 0xc4202f80d0, 0x1, 0x1, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/listeners.go:30 +0x81
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.SyncState(0xc420149658, 0x1, 0x1, 0xc420079380, 0x3ff0000000000000, 0x2503040)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26 +0x14b
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).SyncState(0xc42022a1e0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344 +0x81
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420138ab0, 0x2583680, 0x0, 0x0, 0xc422141040, 0x25, 0x25, 0x2583680, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).sync(0xc42041db00, 0x169d0e0, 0xc420af41e0, 0xc420af41e0, 0xc420af4100)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 +0x626
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.sync)-fm(0x169d0e0, 0xc420af41e0, 0xa, 0xc420911e00)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4209aa030)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420923fa8)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc420f13fa8, 0x12a05f200, 0x0, 0x1, 0xc420951ce0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc420923fa8, 0x12a05f200, 0xc420951ce0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4209aa030, 0x12a05f200, 0xc420951ce0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1081 +0x1f1
```

**Comment by joshrosso** [comment]
@bigkraig, is this fixed with the changes we discussed today on rule evaluation?

**Comment by joshrosso** [comment]
@bigkraig ping

**Comment by bigkraig** [comment]
I think so. I am no longer able to reproduce it 👍
