### ISSUE TITLE
Modifying Target Group params directly causes go panic/pod crash

### ISSUE THREAD

**Issue by bchav** [coreos/alb-ingress-controller#68]
Not sure what the ideal behavior should be here. Perhaps when using the AWS API to directly modify target group values, the controller should observe the new values and modify its own configuration. In this case, I changed HealthyThresholdCount from 5 to 2. 

```
I0419 18:56:15.962284 1 ec2.go:35] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: { SubnetIds: ["subnet-40c35329","subnet-6066be1b","subnet-dd23d590"] } 
I0419 18:56:16.099481 1 ec2.go:35] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: { SubnetIds: ["subnet-40c35329","subnet-6066be1b","subnet-dd23d590"] } 
I0419 18:56:16.131379 1 ec2.go:35] Request: ec2/&{DescribeSecurityGroups POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: { GroupIds: ["sg-28a2d841"] } 
I0419 18:56:16.189473 1 log.go:48] [ALB-INGRESS] [2048-game-2048-alb-ingress] [INFO]: Start TargetGroup creation. 
I0419 18:56:16.189614 1 elbv2.go:43] Request: elasticloadbalancing/&{CreateTargetGroup POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: { HealthCheckIntervalSeconds: 30, HealthCheckPath: "/", HealthCheckPort: "traffic-port", HealthCheckProtocol: "HTTP", HealthCheckTimeoutSeconds: 5, HealthyThresholdCount: 5, Matcher: { HttpCode: "200" }, Name: "tectonic-30159-HTTP-c493193", Port: 30159, Protocol: "HTTP", UnhealthyThresholdCount: 2, VpcId: "vpc-6121a208" } I0419 18:56:16.355021 1 log.go:48] [ALB-INGRESS] [2048-game-2048-alb-ingress] [INFO]: Failed TargetGroup creation. 
Error: DuplicateTargetGroupName: A target group with the same name 'tectonic-30159-HTTP-c493193' exists, but with different settings status code: 400, request id: ddbf0cad-2531-11e7-a6ab-ff20619c78e9. 
I0419 18:56:16.355041 1 log.go:48] [ALB-INGRESS] [2048-game-2048-alb-ingress] [INFO]: Start Listener creation. 
E0419 18:56:16.355161 1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49 /usr/lib/go/src/runtime/asm_amd64.s:479 /usr/lib/go/src/runtime/panic.go:458 /usr/lib/go/src/runtime/panic.go:62 /usr/lib/go/src/runtime/sigpanic_unix.go:24 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:89 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:69 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listeners.go:30 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 /usr/lib/go/src/runtime/asm_amd64.s:2086 panic: runtime error: invalid memory address or nil pointer dereference [recovered] panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x8474d6] goroutine 123 [running]: panic(0x16d4600, 0xc420014030) /usr/lib/go/src/runtime/panic.go:500 +0x1a1 github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126 panic(0x16d4600, 0xc420014030) /usr/lib/go/src/runtime/panic.go:458 +0x243 github.com/coreos/alb-ingress-controller/controller/alb.(*Listener).create(0xc42068e840, 0xc4200bab40, 0xc420730c40, 0x1a) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:89 +0x96 github.com/coreos/alb-ingress-controller/controller/alb.(*Listener).SyncState(0xc42068e840, 0xc4200bab40, 0x0) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listener.go:69 +0x9c github.com/coreos/alb-ingress-controller/controller/alb.Listeners.SyncState(0xc420120b10, 0x1, 0x1, 0xc4200bab40, 0xc4200bab70, 0x1, 0x1, 0xc420657a50) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/listeners.go:30 +0x81 github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.SyncState(0xc420022738, 0x1, 0x1, 0x2408700, 0xc4201c5aa0, 0x2408700) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26 +0x149 github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).SyncState(0xc42061bc70) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344 +0x81 github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420104360, 0xc4201d2ce8, 0x0, 0x8, 0xc420626340, 0x2, 0x2, 0x2477f88, 0x0, 0x0) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107 +0x76 github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).sync(0xc42077c360, 0x15f3960, 0xc420627820, 0xc420627820, 0xc420627700) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 +0x68f github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.sync)-fm(0x15f3960, 0xc420627820, 0xa, 0xc4206d5dd0) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 +0x3e github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4207509c0) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 +0x101 github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm() /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420657f58) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc420657f58, 0x12a05f200, 0x0, 0x1, 0xc4206f9380) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc420657f58, 0x12a05f200, 0xc4206f9380) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4207509c0, 0x12a05f200, 0xc4206f9380) /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x55 created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start /home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1081 +0x1f1 
```

**Comment by bigkraig** [comment]
@bchav can you check if the #69 PR fixes the problem for you?

**Comment by joshrosso** [comment]
Closing this for now. Please re-open if needed.

Still need to discuss what we're willing to 'modify' in certain cases, but we'll circle back later.
