### ISSUE TITLE
Segfault / failure when `TooManyLoadBalancers`, or thereabouts

### ISSUE THREAD

**Issue by darrengarvey** [coreos/alb-ingress-controller#95]
I've hit an issue when there are "not enough" free ELB slots available in a zone.

This issue happens when there are no slots - the controller segfaults and crash loops. Strangely though, the trace below is when there is *one* free ELB slot. I see in the AWS console that the ALB is created and it looks fine, although the service doesn't ever get exposed to the requested hostname.

I would expect the controller to only want to create one ALB, so I'm not sure why the error is being raised.

For reference, I'm on kubernetes 1.5.2 and the Ingress is created like this:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "bacchus-alb-ingress"
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: 'subnet-1, subnet-2'
    alb.ingress.kubernetes.io/security-groups: sg-1
    kubernetes.io/ingress.class: "alb"
  labels:
    app: my-service-alb-ingress
spec:
  rules:
  - host: my-hostname
    http:
      paths:
      - path: /
        backend:
          serviceName: "my-service"
          servicePort: 80
```
The error logs for alb-ingress-controller look like this:
```
I0511 10:19:22.276600       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 0 ingresses from existing AWS resources
I0511 10:19:22.276762       1 launch.go:96] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0511 10:19:22.276995       1 launch.go:232] Creating API server client for https://6.5.4.3:443
I0511 10:19:22.286507       1 launch.go:115] validated kube-system/default-http-backend as the default backend
I0511 10:19:22.291880       1 controller.go:1071] starting Ingress controller
I0511 10:19:22.294509       1 controller.go:168] ignoring add for ingress <my-ingress-name> based on annotation kubernetes.io/ingress.class
I0511 10:19:22.325245       1 leaderelection.go:188] sucessfully acquired lease kube-system/ingress-controller-leader
W0511 10:19:23.298081       1 queue.go:87] requeuing kube-system/ingress-controller-leader, err deferring sync till endpoints controller has synced
I0511 10:19:32.858510       1 ec2.go:35] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  SubnetIds: ["subnet-<b33f>","subnet-<9157>"]
}
I0511 10:19:32.907021       1 ec2.go:35] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  SubnetIds: ["subnet-<b33f>","subnet-<9157>"]
}
I0511 10:19:32.931396       1 ec2.go:35] Request: ec2/&{DescribeSecurityGroups POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  GroupIds: ["sg-<5ec012>"]
}
I0511 10:19:32.961467       1 ingress.go:112] default-<my-ingress-name>: default/api service is not of type NodePort
I0511 10:19:32.961484       1 log.go:48] [ALB-INGRESS] [default-<my-ingress-name>] [INFO]: Start ELBV2 (ALB) creation.
I0511 10:19:32.961716       1 elbv2.go:43] Request: elasticloadbalancing/&{CreateLoadBalancer POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  Name: "<some-generated-id>",
  Scheme: "internet-facing",
  SecurityGroups: ["sg-<5ec012>"],
  Subnets: ["subnet-<b33f>","subnet-<9157>"],
  Tags: [{
      Key: "Namespace",
      Value: "default"
    },{
      Key: "IngressName",
      Value: "<my-ingress-name>"
    },{
      Key: "Hostname",
      Value: "<my-requested-hostname>"
    }]
}
I0511 10:19:32.989939       1 log.go:62] [ALB-INGRESS] [TooManyLoadBalancers: The maximum number of load balancers has been reached
	status code: 400, request id: <request-id>] [ERROR]: Failed to create ELBV2 (ALB). Error: %!s(MISSING)
E0511 10:19:32.990065       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/usr/lib/go/src/runtime/asm_amd64.s:479
/usr/lib/go/src/runtime/panic.go:458
/usr/lib/go/src/runtime/panic.go:62
/usr/lib/go/src/runtime/sigpanic_unix.go:24
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:55
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:24
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/usr/lib/go/src/runtime/asm_amd64.s:2086
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x84b5d6]

goroutine 87 [running]:
panic(0x16d4600, 0xc420012030)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x16d4600, 0xc420012030)
	/usr/lib/go/src/runtime/panic.go:458 +0x243
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).SyncState(0x0, 0xc4205a6e60, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:55 +0x26
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.SyncState(0xc420112600, 0x1, 0x1, 0x2408700, 0xc4206d8da0, 0x2408700)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:24 +0xa0
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).SyncState(0xc4204fadc0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344 +0x81
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420105050, 0xc4205ffd20, 0x0, 0x8, 0xc420112068, 0x1, 0x1, 0x2477f88, 0x0, 0x0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).sync(0xc4202118c0, 0x15f3960, 0xc4205d3f30, 0xc4205d3f30, 0xc4205d3f00)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 +0x68f
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.sync)-fm(0x15f3960, 0xc4205d3f30, 0xa, 0xc420737dd0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4206cf0e0)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 +0x101
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420783f58)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc420783f58, 0x12a05f200, 0x0, 0x1, 0xc4206c7440)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc420783f58, 0x12a05f200, 0xc4206c7440)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4206cf0e0, 0x12a05f200, 0xc4206c7440)
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x55
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/josh/dev/go/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1081 +0x1f1
```

**Comment by joshrosso** [comment]
Thanks for the report @darrengarvey 

Before I dig too deep, can you verify you're running a newer version of the controller?

See versions here: https://quay.io/application/coreos/alb-ingress-controller. Apologies in advanced for the commit-based sku. Once we knock out some high priority items we're going to a more standardized release structure!

**Comment by darrengarvey** [comment]
Hi @joshrosso. I was on 0.8. Just tried `latest` (from https://quay.io/repository/coreos/alb-ingress-controller), aka. `a4590a10` as well as 0.8 as the `TooManyLoadbalancers` error is no longer being shown, but the segfault remains.

The number of actual load balancers is identical to Friday when the issue showed up, so I'm not sure why the difference. The logs preceding the POST to `CreateLoadBalancer` are the same as above, but the following has a slightly different message:

```I0515 11:33:59.030696       1 log.go:48] [ALB-INGRESS] [default-foo-alb-ingress] [INFO]: Completed ELBV2 (ALB) creation. Name: foo-9fe269cfd045125 | ARN: arn:aws:elasticloadbalancing:region:1234567890:loadbalancer/app/foo-9fe269cfd045125/61386c4c62ea475
E0515 11:33:59.030924       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/signal_unix.go:290
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:349
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/controller.go:110
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x1526b57]

goroutine 90 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x1782060, 0x2551b40)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).Reconcile(0x0, 0xc4202f6fa0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:60 +0x37
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.Reconcile(0xc42000c790, 0x1, 0x1, 0xc42000c798, 0xc4206539f0, 0xc42000c798, 0xc420659da0, 0x3ff0000000000000)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:26 +0xb7
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).Reconcile(0xc4206539f0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:349 +0x9a
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420222510, 0x2586680, 0x0, 0x0, 0xc42011c030, 0x1, 0x1, 0x2586680, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/controller.go:110 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).sync(0xc4203239e0, 0x169f060, 0xc42052ccf0, 0xc42052ccf0, 0xc42052cc00)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 +0x626
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.sync)-fm(0x169f060, 0xc42052ccf0, 0xa, 0xc4206bce00)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc420728030)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc420759fa8)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc4208f7fa8, 0x12a05f200, 0x0, 0x1, 0xc4204b5080)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc420759fa8, 0x12a05f200, 0xc4204b5080)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc420728030, 0x12a05f200, 0xc4204b5080)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1081 +0x1f1
```

**Comment by darrengarvey** [comment]
I wonder if this problem is we haven't set up the permissions correctly and alb-ingress-controller just isn't dealing with that.

For instance, I don't see any TargetGroups or Rules being created after the Ingress rule is created and ALB + Route53 have been set up. I'll try digging a bit more.

**Comment by darrengarvey** [comment]
Ah, please ignore the latter error - this is down to missing some IAM permissions. I'll create a PR to give some better logging about that.

**Comment by justinclayton** [comment]
I'm getting this segfault issue as well after any unhappy response from AWS during ALB creation. This includes anything from 403s due to bad IAM config to ALB naming validation errors (because my `CLUSTER_NAME` had a dot in it). If the ALB fails to create, the segfault occurs:

```
I0523 19:39:37.414352       1 log.go:62] [ALB-INGRESS] [ValidationError: The load balancer name 'aws.lab-d044d10667b39a8' can only contain characters that are alphanumeric characters and hyphens(-)
	status code: 400, request id: 8e3ac8af-3fef-11e7-a872-73c76d1e15c0] [ERROR]: Failed to create ELBV2 (ALB). Error: %!s(MISSING)
E0523 19:39:37.414498       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
```

**Comment by justinclayton** [comment]
I take it back...I'm still getting the crash even after successful ALB creation :-(

**Comment by bigkraig** [comment]
Can you guys try it with the latest code? Some changes have been made to reduce the amount of nil pointer dereferencing.

**Comment by joshrosso** [comment]
Please reopen if it persists with newer build, specifically image `b30d8d28` or later.
